spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        profileView: profile_view_channel
        projectView: project_view_channel
        follower: follower_channel
        postPublished: post_published_channel
        postView: post_view_channel
        postLike: post_like_channel
        postComment: post_comment_channel
        skillReceived: skill_received_channel
        recommendationReceived: recommendation_received_channel
        addedToFavorites: added_to_favorites_channel
        projectInvite: project_invite_channel
        taskCompleted: task_completed_channel
        goalCompleted: goal_completed_channel
        achievementReceived: achievement_received_channel
        profileAppearedResearch: profile_appeared_research
        projectAppearedResearch: project_appeared_research

server:
  port: 8086

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
