spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: record
    consumer:
      security:
        protocol: PLAINTEXT
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        spring.json.use.type.headers: false
      project-view:
        topic: "project-view"
        group-id: "project-view-group"
        trusted-packages: "*"
        max.poll.records: 100
        max.poll.interval.ms: 10000
        fetch.max.wait.ms: 5000
      recommendation-create:
        topic: "recommendation-create"
        group-id: "recommendation-create-group"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        profile-view: profile_view_channel

server:
  port: 8086

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082