spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        profile-view: profile_view_channel
        comment_event: comment_event_channel
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        timeout: 6000ms

logging:
  level:
    root: info
