spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    producer:
      acks: all
      security:
        protocol: PLAINTEXT
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      project_view:
        topic: "project-view"