openapi: 3.0.0
info:
  title: Analytics Service API
  description: OpenAPI documentation for Analytics Service
  version: 1.0.0
servers:
  - url: http://localhost:8086
    description: Local development server
paths:
  #  AnalyticsEvent paths
  /api/v1/analytics-events:
    get:
      tags:
        - Analytics Event
      summary: Retrieve analytics events
      description: Get a list of analytics events with filtering by period
      parameters:
        - name: receiver-id
          in: query
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - name: event-type
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/EventType"
        - name: filters
          in: query
          schema:
            $ref: "#/components/schemas/AnalyticsEventFilterDto"
        - name: x-user-id
          in: header
          description: User ID header
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Successful request, retrieving the list of event analytics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnalyticsEventDto"

components:
  schemas:
    Interval:
      type: string
      enum: [ DAY, WEEK, MONTH, YEAR ]
      description: Time periods

    EventType:
      type: string
      enum: [
        PROFILE_VIEW,
        PROJECT_VIEW,
        FOLLOWER,
        POST_PUBLISHED,
        POST_VIEW,
        POST_LIKE,
        POST_COMMENT,
        SKILL_RECEIVED,
        RECOMMENDATION_RECEIVED,
        ADDED_TO_FAVOURITES,
        PROJECT_INVITE,
        TASK_COMPLETED,
        GOAL_COMPLETED,
        ACHIEVEMENT_RECEIVED,
        PROFILE_APPEARED_IN_SEARCH,
        PROJECT_APPEARED_IN_SEARCH
      ]
      description: Event types

    AnalyticsEventFilterDto:
      type: object
      properties:
        interval:
          $ref: "#/components/schemas/Interval"
        from:
          type: string
          example: 2023-12-12T00:00:00
          description: Filter from a specific date
        to:
          type: string
          example: 2024-12-12T00:00:00
          description: Filter until a specific date

    AnalyticsEventDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: Event analytics ID
        receiverId:
          type: integer
          format: int64
          example: 2
          description: Receiver ID
        actorId:
          type: integer
          format: int64
          example: 1
        eventType:
          $ref: "#/components/schemas/EventType"
        receivedAt:
          type: string
          example: 2024-10-08 07:09:11
