name: CI

on:
  push:
    branches:
      - unicorn-master-bc3
  pull_request:
    branches:
      - unicorn-master-bc3

jobs:
  run_tests:

    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_database
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 8s
          --health-timeout 3s
          --health-retries 3


    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Azul JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Gradle
        run: ./gradlew build

      - name: Run Gradle tests
        run: ./gradlew test