name: CI Pipeline

# Триггеры для запуска workflow
on:
  push:
    branches:
      - cerberus-master-stream6 # Запуск при пуше в ветку
  pull_request:
    branches:
      - cerberus-master-stream6 # Запуск на pull request в ветку

jobs:
  build:
    # Указываем виртуальную машину, на которой будет выполняться задача
    runs-on: ubuntu-latest

    # Определяем шаги для сборки
    steps:
      - name: Checkout code # Шаг: Клонирование кода
        uses: actions/checkout@v4

      - name: Set up JDK 17 # Шаг: Установка Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Используем Temurin JDK
          java-version: '17'

      - name: Cache Gradle dependencies  # Шаг: Кэширование зависимостей Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build with Gradle  # Шаг: Сборка проекта с помощью Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests  # Шаг: Запуск тестов
        run: ./gradlew test --no-daemon

      - name: Publish Test Results  # Шаг: Публикация результатов тестов
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test